---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/git-commit: 0e13b5a520dcd47480a8cd9c941d827148b0db27
    fabric8.io/git-branch: master
    fabric8.io/git-url: https://github.com/RaJoBra/KundeTest.git
  labels:
    app: kunde
    provider: fabric8
    version: "1.0"
    group: de.hska
  name: kunde
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: kunde
    provider: fabric8
    group: de.hska
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 0e13b5a520dcd47480a8cd9c941d827148b0db27
        fabric8.io/git-branch: master
        fabric8.io/git-url: https://github.com/RaJoBra/KundeTest.git
      labels:
        app: kunde
        provider: fabric8
        version: "1.0"
        group: de.hska
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: hska/kunde:1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8444
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: spring-boot
        ports:
        - containerPort: 8444
          name: pcsync-http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8444
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
